language: python
python:
  - "3.7"      # current default Python on Travis CI
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m pytest test_cc.py
  - coverage report -m
after_install: 
  - coveralls
